AFS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',  include('apps.core.urls'),name="home"),
    path('eumandoaqui/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jogos/', include('apps.jogos.urls')),
    path('equipamentos/', include('apps.equipamentos.urls',namespace='equipamentos')),
    path('core/', include('apps.core.urls')),
    path('atletas/', include('apps.atletas.urls',namespace='atletas')),
    path('api/', include('apps.api.urls',namespace='api'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

apps/equipamentos/urls.py
from django.urls import path
from . import views

app_name = 'equipamentos'
urlpatterns = [
    path('encomendas_equipamentos/<str:status>/', views.EncomendaEquipamentosListView.as_view(), name='encomendas_equipamentos_list'),
    path('create_encomenda_equipamentos/', views.EncomendaItemCreateView.as_view(), name='create_encomenda_equipamentos'),
    path('create_tamanho/', views.TamanhoCreateView.as_view(), name='create_tamanho'),
    path('update_tamanho/<int:pk>/', views.TamanhoUpdateView.as_view(), name='update_tamanho'),
    path('delete_tamanho/<int:pk>/', views.tamanho_delete, name='delete_tamanho'),
    path('create_equipamentos/', views.EquipamentosCreateView.as_view(), name='create_equipamentos'),
    path('update_equipamentos/<int:pk>/', views.EquipamentosUpdateView.as_view(), name='update_equipamentos'),
    path('delete_equipamentos/<int:pk>/', views.equipamentos_delete, name='delete_equipamentos'),
    path('encomenda_delete/<int:pk>/', views.encomenda_delete, name='encomenda_delete'),
    path('encomendas_por_atleta/<str:pk>/<str:status>/', views.encomendas_por_atleta, name='encomendas_por_atleta'),
    path('encomendas_uptade/<int:pk>/', views.EncomendaItemUpdateView.as_view(), name='encomendas_uptade'),
    path('alterar_estado_encomenda/<int:pk>/', views.alterar_estado_encomenda, name='alterar_estado_encomenda'),
    path('pdf_encomendas_atletas/', views.gerar_pdf_encomendas, name='pdf_encomendas_atletas'),
]

apps/equipamentos/models.py
from django.db import models
from apps.atletas.models import Atleta


class Tamanho(models.Model):
    tamanho = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.tamanho



class Equipamentos(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)





    def __str__(self):
        return self.nome

class Encomenda(models.Model):
    atleta = models.ForeignKey(Atleta, on_delete=models.CASCADE)
    tamanho = models.ForeignKey(Tamanho, on_delete=models.CASCADE, null=True, blank=True)
    data_pedido = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Encomenda de {self.atleta} em {self.tamanho}"

class EncomendaItem(models.Model):
    encomenda = models.ForeignKey(Encomenda, on_delete=models.CASCADE,blank=True)
    equipamento = models.ForeignKey(Equipamentos, on_delete=models.PROTECT)
    entregue = models.BooleanField(default=False)
    data_entrega = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"Encomenda de {self.encomenda.atleta} para {self.equipamento}"


def encomenda_kit(atleta, tamanho):
    encomendas_criadas = []
    todos_equipamentos = Equipamentos.objects.all()
    for equipamento in todos_equipamentos:
        if equipamento.nome == "jogo principal" and not atleta.guarda_redes:
            encomenda = Encomenda.objects.create(
                atleta=atleta,
                tamanho = tamanho)
            EncomendaItem.objects.create(
                encomenda=encomenda,
                equipamento=equipamento,
                entregue=False)
            encomendas_criadas.append(encomenda)
        elif equipamento.nome == 'guarda-redes azul' and atleta.guarda_redes:
            encomenda = Encomenda.objects.create(
                atleta=atleta,
                tamanho=tamanho)
            EncomendaItem.objects.create(
                encomenda=encomenda,
                equipamento=equipamento,
                entregue=False)
        elif equipamento.nome == 'fato de treino':
            encomenda = Encomenda.objects.create(
                atleta=atleta,
                tamanho=tamanho)
            EncomendaItem.objects.create(
                encomenda=encomenda,
                equipamento=equipamento,
                entregue=False)
        elif equipamento.nome == 'kit treino jogador':
            encomenda = Encomenda.objects.create(
                atleta=atleta,
                tamanho=tamanho)
            EncomendaItem.objects.create(
                encomenda=encomenda,
                equipamento=equipamento,
                entregue=False)
        elif equipamento.nome == 'polo de saída':
            encomenda = Encomenda.objects.create(
                atleta=atleta,
                tamanho=tamanho)
            EncomendaItem.objects.create(
                encomenda=encomenda,
                equipamento=equipamento,
                entregue=False)
        elif equipamento.nome == 'mochila':
            encomenda = Encomenda.objects.create(
                atleta=atleta,
                tamanho=tamanho)
            EncomendaItem.objects.create(
                encomenda=encomenda,
                equipamento=equipamento,
                entregue=False)

apps/equipamentos/forms.py
from django import forms
from apps.atletas.models import Atleta
from .models import Equipamentos, Tamanho, EncomendaItem, Encomenda


class TamanhoForm(forms.ModelForm):
    class Meta:
        model = Tamanho
        fields = ['tamanho']

        widgets = {
            'tamanho': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tamanho do equipamento'}),
        }




class EquipamentosForm(forms.ModelForm):
    class Meta:
        model = Equipamentos
        fields = ['nome', 'descricao']

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do equipamento'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descrição do equipamento'}),
        }


class EncomendaForm(forms.ModelForm):
    class Meta:
        model = Encomenda
        fields = ['atleta', 'tamanho']

        widgets = {
            'atleta': forms.Select(attrs={'class': 'form-control'}),
            'tamanho': forms.Select(attrs={'class': 'form-control'}),
        }


class EncomendaItemForm(forms.ModelForm):
    class Meta:
        model = EncomendaItem
        fields = ['equipamento']

        widgets = {
            'equipamento': forms.Select(attrs={'class': 'form-control'}),
        }

apps/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render



@login_required
def home(request):
    return render(request, 'core/index.html')

apps/equipamentos/views.py
from django.http import FileResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.templatetags.static import static
from django.template.loader import render_to_string
from django.views.generic import CreateView, DetailView, ListView,UpdateView
from django.views.decorators.csrf import csrf_exempt
import json
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import  TA_CENTER
from apps.atletas.models import Atleta
from apps.equipamentos.models import Equipamentos, Tamanho, EncomendaItem, Encomenda, encomenda_kit
from apps.equipamentos.forms import EquipamentosForm,EncomendaItemForm , TamanhoForm, EncomendaForm


# Views and functions for Tamanho
class TamanhoCreateView(CreateView):
    model = Tamanho
    form_class = TamanhoForm
    success_url = reverse_lazy('equipamentos:encomendas_equipamentos_list')
    template_name = 'equipamentos/tamanho_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TamanhoForm()
        return context
    def form_invalid(self, form):
        return super().form_invalid(form)
    def form_valid(self, form):
        return super().form_valid(form)

class TamanhoUpdateView(CreateView):
    model = Tamanho
    form_class = TamanhoForm
    success_url = reverse_lazy('equipamentos:encomendas_equipamentos_list')
    template_name = 'equipamentos/tamanho_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TamanhoForm()
        return context

    def form_invalid(self, form):
        return super().form_invalid(form)

    def form_valid(self, form):
        return super().form_valid(form)

def tamanho_delete(request, pk):
    if request.method == 'POST':
        tamanho = Tamanho.objects.get(pk=pk)
        tamanho.delete()
    return redirect('equipamentos: equipamentos_list')

# Views and functions for  Equipamentos

class EquipamentosCreateView(CreateView):
    model = Equipamentos
    form_class = EquipamentosForm
    success_url = reverse_lazy('equipamentos:encomendas_equipamentos_list')
    template_name = 'equipamentos/equipamentos_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = EquipamentosForm()
        return context

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            html_form = render_to_string(self.template_name, {'form': form}, request=self.request)
            htm = {'html-form': html_form}
            return JsonResponse({'success': False ,'html-form': htm}, status=400)
        return super().form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
             return JsonResponse({'success': True ,'mensagem': "Encomenda criada com sucesso!"})
        return super().form_valid(form)




class EquipamentosUpdateView(CreateView):
    model = Equipamentos
    form_class = EquipamentosForm
    success_url = reverse_lazy('equipamentos:encomendas_equipamentos_list')
    template_name = 'equipamentos/equipamentos_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = EquipamentosForm()
        return context

    def form_invalid(self, form):
        return super().form_invalid(form)

    def form_valid(self, form):
        return super().form_valid(form)



# Views and functions for EncomendaEquipamentos

class EncomendaEquipamentosListView(ListView):
    model = EncomendaItem
    template_name = 'equipamentos/encomenda_equipamentos_list.html'
    context_object_name = 'encomenda_equipamentos'


    def get_queryset(self):
        queryset = EncomendaItem.objects.all()
        status = self.request.GET.get('status')
        print(status)
        if status == 'todos':
            queryset = EncomendaItem.objects.all()
        elif status == 'true':
            queryset = EncomendaItem.objects.filter(entregue=True)
        elif status == 'false':
            queryset = EncomendaItem.objects.filter(entregue=False)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['atletas'] = Atleta.objects.all()
        return context
    
    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['equipamentos/encomenda_equipamentos_list_partial.html']
        return ['equipamentos/encomenda_equipamentos_list.html']

class EncomendaItemCreateView(CreateView):
    def get(self,request):
        form_encomenda  = EncomendaForm()
        form_item= EncomendaItemForm()
        

        template = 'equipamentos/encomenda_item_create_partial.html' if request.headers.get('HX-Request') or request.headers.get('x-requested-with') == 'XMLHttpRequest' else 'equipamentos/encomenda_item_create.html'

        return render(request, template, {'form_encomenda': form_encomenda, 'form_item': form_item})
    
    def post(self,request):
        form_encomenda = EncomendaForm(request.POST)
        form_item = EncomendaItemForm(request.POST)
        if form_encomenda.is_valid() and form_item.is_valid():
            encomenda = form_encomenda.save()
            artigos = form_item.save(commit=False)
            equipamentos = form_item.cleaned_data['equipamento']
            if equipamentos.nome == "Kit Completo":
                print("Kit Completo")
                atleta = form_encomenda.cleaned_data['atleta']
                tamanho = form_encomenda.cleaned_data['tamanho']
                encomenda_kit(atleta,tamanho)
            else:
                artigos.encomenda = encomenda
                artigos.atleta = form_encomenda.cleaned_data['atleta']
                artigos.save()
            return JsonResponse({'success': True ,'message': "Encomenda criada com sucesso!"})
        else:
            html_form = render_to_string('equipamentos/encomenda_item_create.html', {'form_encomenda':form_encomenda,'form_item':form_item}, request=self.request)
            htlm = {'html-form': html_form}
            return JsonResponse({'success': False ,'html-form': htlm}, status=400)
        
    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['equipamentos/encomenda_item_create_partial.html']
        return ['equipamentos/encomenda_item_create.html']
    

    
        
class EncomendaItemUpdateView(UpdateView):
    def get(self, request, pk):
        item = get_object_or_404(EncomendaItem, pk=pk)
        form_encomenda = EncomendaForm(instance=item.encomenda)
        form_item = EncomendaItemForm(instance=item)
        template = 'equipamentos/encomenda_item_create_partial.html' if request.headers.get('HX-Request') or request.headers.get('x-requested-with') == 'XMLHttpRequest' else 'equipamentos/encomenda_item_create.html'

        return render(request, template, {'form_encomenda': form_encomenda, 'form_item': form_item})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['aqui'] = EncomendaItemForm(instance=self.object)
        return context

    def post(self, request, pk):
        item = get_object_or_404(EncomendaItem, pk=pk)
        form_encomenda = EncomendaForm(request.POST, instance=item.encomenda)
        form_item = EncomendaItemForm(request.POST, instance=item)

        if form_encomenda.is_valid() and form_item.is_valid():
            encomenda = form_encomenda.save()
            artigos = form_item.save(commit=False)
            equipamento = form_item.cleaned_data['equipamento']

            if equipamento.nome == "Kit Completo":
                atleta = form_encomenda.cleaned_data['atleta']
                tamanho = form_encomenda.cleaned_data['tamanho']
                encomenda_kit(atleta, tamanho)
            else:
                artigos.encomenda = encomenda
                artigos.atleta = form_encomenda.cleaned_data['atleta']
                artigos.save()

            return JsonResponse({'success': True, 'message': "Encomenda editada com sucesso!"})

        else:
            html_form = render_to_string(
                'equipamentos/encomenda_item_create.html',
                {'form_encomenda': form_encomenda, 'form_item': form_item},
                request=request
            )
            return JsonResponse({'success': False, 'html_form': html_form}, status=400)

    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            print("ajax")
            return ['equipamentos/encomenda_item_create_partial.html']
        return ['equipamentos/encomenda_item_create.html']



def encomenda_delete(request,pk):
    try:
        encomenda = EncomendaItem.objects.get(pk=pk)
        encomenda.delete()
        return JsonResponse({'success': True,'message': f"Encomenda de  {encomenda.encomenda.atleta} eliminada com sucesso!"})
    except:
        return JsonResponse({'success': False,'message': "Erro ao eliminar encomenda!"}, status=400)
def equipamentos_delete(request, pk):
    try:
        equipamentos = Equipamentos.objects.get(pk=pk)
        equipamentos.delete()
        return JsonResponse({'success': True,'message': f"Equipamento {equipamentos.nome} eliminado com sucesso!"})
    except:

apps/core/templates/equipamentos/encomenda_equipamentos_list.html
{% extends 'base.html' %}

{% block main %}
{% include 'equipamentos/encomenda_equipamentos_list_partial.html' %}
{% endblock %}

apps/core/templates/equipamentos/encomenda_equipamentos_list_partial.html
{% load static %}





<div class="container-atletas">

    <div class="header d-flex mb-3">
        <div class="me-auto p-2">
            <h1 class="titulo">Encomendas equipamento</h1>
        </div>
        <div class="p-2">
            <select name="atletas" id="atletasSelect" onchange="atletaSelectEncomendas()">
            <option value="todosAtletas" disabled selected>Selecione um atleta</option>
            <option value="todos">Selecionar todos</option>
            {% for atleta in atletas %}
            <option value='{{atleta.id}}'>{{ atleta.nome }}</option>
            {% endfor %}
        </select>

        <select name="estadoEncomenda" id="estadoEncomendaSelect" onchange="atletaSelectEncomendas()">
            <option value="todos" disabled selected>Selecione um estado</option>
            <option value="entregue">Entregue</option>
            <option value="pendente">Pendente</option>
            <option value="todos">Selecionar todos</option>
        </select>
        </div>
        <div class="p-2">
            <a href="{% url 'equipamentos:create_encomenda_equipamentos' %}" class="btn-add link-ajax"><span
                class="material-symbols-outlined btn-operacoes">add</span>Nova Encomenda</a>
        </div>
        
        
        
    </div>

    <div class="table-responsive">
        <div class="table-container">
            <table class="table-encomendas">
                <thead>
                    <tr>
                        <th><input type="checkbox" type="checkbox" class="form-check-input selectEncomendaAll"
                                id='selectall'></th>
                        <th>Nome</th>
                        <th>Artigo</th>
                        <th>Tamanho</th>
                        <th>Data Encomenda</th>
                        <th>Entregue</th>
                        <th>Operações</th>
                    </tr>
                </thead>

                <tbody>


                    {% for encomenda in encomenda_equipamentos %}
                    <tr>
                        <td>
                            <input type="checkbox" class="form-check-input selectEncomenda" value="{{ encomenda.id }}">

                        </td>
                        <td>
                            <a class="nomeAtleta" href="#">{{ encomenda.encomenda.atleta }}</a>
                        </td>
                        <td>
                            {{ encomenda.equipamento }}
                        </td>
                        <td>
                            {{ encomenda.encomenda.tamanho }}
                        </td>
                        <td>
                            {{ encomenda.encomenda.data_pedido }}
                        </td>
                        <td>
                            <input onchange="alterarEstadoEncomenda('{{ encomenda.id }}')" type="checkbox"
                                class="form-check-input estadoEncomenda" {% if encomenda.entregue %}checked{% endif %}>

                        </td>
                        <td class="linha">
                            <a href="{% url 'equipamentos:encomendas_uptade' encomenda.id %}"
                                 hx-swap="outerHTML" hx-push-url="true" class="link-ajax"><span
                                    class="material-symbols-outlined btn-operacoes">edit</span></a>
                            <a href="#" class="link-ajax"
                                onclick="deleteEncomenda('{{ encomenda.id }}','{{ encomenda.encomenda.atleta }}','{{ encomenda.equipamento }}')"><span
                                    class="material-symbols-outlined btn-operacoes link-ajax">delete</span></a>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
</div>

<div class="header">
    <div class="me-auto">
        <a href="#" class="btn-add pdf-encomendas">
        <span class="material-symbols-outlined">print</span>
        Gerar PDF de Encomendas</a>
    </div>

</div>

<script>

    $(function () {
        $(".selectEncomendaAll").click(function () {
            if ($(this).is(":checked")) {
                console.log("checked");
                $('.selectEncomenda').prop('checked', true);
            } else {
                $('.selectEncomenda').prop('checked', false);
            }
        })
    })


</script>