AFS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',  include('apps.core.urls'),name="home"),
    path('eumandoaqui/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jogos/', include('apps.jogos.urls')),
    path('equipamentos/', include('apps.equipamentos.urls',namespace='equipamentos')),
    path('core/', include('apps.core.urls')),
    path('atletas/', include('apps.atletas.urls',namespace='atletas')),
    path('api/', include('apps.api.urls',namespace='api'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/atletas/urls.py
from django.urls import path
from . import views
from apps.atletas.views import atletas_delete

app_name = 'atletas'

urlpatterns = [
    path('atletas_list/', views.AtletaListView.as_view(), name='atletas_list'),
    path('create_atleta/', views.AtletaCreateView.as_view(), name='create_atleta'),
    path('atleta_detail/<int:pk>/', views.AtletaDetailView.as_view(), name='detail_atleta'),
    path('update_atleta/<int:pk>/', views.AtletaUpdateView.as_view(), name='update_atleta'),
    path('delete_atleta/<int:pk>/', atletas_delete, name='delete_atleta'),
    path('pdf_camisolas_atletas/', views.gerar_pdf_camisolas_atletas, name='pdf_camisolas_atletas'),
    path('atletas_list_escalao/', views.atletas_escalao_json, name='atletals_list_escalao'),
    path('pdf_atletas_escalao_pdf/', views.gerar_pdf_lista_atletas, name='pdf_atletas_escalao'),
]

apps/atletas/models.py
from django.db import models
from apps.jogos.models import Equipas



class Atleta(models.Model):
    nome = models.CharField(max_length=100)
    data_nascimento = models.DateField()
    numero = models.IntegerField()
    encarregado = models.CharField(max_length=100)
    telefone = models.CharField(max_length=20)
    email = models.EmailField()
    guarda_redes = models.BooleanField(default=False)
    ficha = models.FileField(upload_to='fichas/', null=True, blank=True)
    nome_camisola = models.CharField(max_length=100, null=True, blank=True)
    equipa = models.ForeignKey(Equipas, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.nome

apps/atletas/forms.py
from django import forms
from apps.atletas.models import Atleta
from django.utils import timezone
from apps.jogos.models import Equipas


class AtletaForm(forms.ModelForm):
    
    class Meta:
        model = Atleta
        fields = ['nome', 'data_nascimento', 'numero', 'nome_camisola', 'encarregado', 'telefone', 'email','equipa', 'guarda_redes', 'ficha']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do atleta'}),
            'data_nascimento': forms.DateInput(attrs={'class': 'form-control datepicker', 'placeholder': 'Data de nascimento',                                       'type': 'date'}),
            'numero': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Número do atleta'}),
            'nome_camisola': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome da camisola do atleta'}),
            'encarregado': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Encarregado do atleta'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefone do atleta'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email do atleta'}),
            'guarda_redes': forms.CheckboxInput(attrs={'class': 'form-check-input', 'placeholder': 'Guarda redes do atleta'}),
            'equipa': forms.Select(attrs={'class': 'form-control'}),
            'ficha': forms.FileInput(attrs={'class': 'form-control', 'placeholder': 'Ficha do atleta'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        data_nascimento = cleaned_data.get('data_nascimento')
        numero = cleaned_data.get('numero')

        if data_nascimento and numero:
            ano_nascimento = data_nascimento.year
            conflitos = Atleta.objects.filter(data_nascimento__year=ano_nascimento, numero=numero)
            if self.instance.pk:
                conflitos = conflitos.exclude(pk=self.instance.pk)
            if conflitos.exists():
                self.add_error(None, "Já existe um atleta com o mesmo número e ano de nascimento.")
    def __init__(self, *args, **kwargs):
        super(AtletaForm, self).__init__(*args, **kwargs)
        self.fields['ficha'].required = False
        

apps/atletas/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.template.loader import render_to_string
from django.core import serializers
from django.utils.timezone import datetime
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from apps.atletas.models import Atleta
from apps.atletas.forms import AtletaForm
from apps.jogos.models import Jogos, Equipas
from apps.equipamentos.models import EncomendaItem

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import  TA_CENTER


class AtletaListView(ListView):
    model = Atleta
    template_name = 'atletas/atletas_list.html'
    context_object_name = 'atletas'

    def get_queryset(self):
        return Atleta.objects.all().order_by('data_nascimento')

    def get_context_data(self, **kwargs):
        context = super(AtletaListView, self).get_context_data(**kwargs)
        context['altetas'] = Atleta.objects.all()
        context['jogos'] = Jogos.objects.all()
        context['equipas'] = Equipas.objects.filter(nome__contains='AVS').order_by('nome')
        return context
    
    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['atletas/atletas_list_partial.html']
        return ['atletas/atletas_list.html']

class AtletaCreateView(CreateView):
    model = Atleta
    form_class = AtletaForm
    template_name = 'atletas/atleta_form.html'

    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['atletas/atleta_form_partial.html']
        return ['atletas/atleta_form.html']

    def get_context_data(self, **kwargs):
        context = super(AtletaCreateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        self.object = form.save()
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': True ,'message': "Atleta criado com sucesso!"})
        return super().form_valid(form)
    
    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            errors = form.errors.get_json_data() 
            html_form = render_to_string('atletas/atleta_form_partial.html', {'form': form}, request=self.request)  
            htm = {'html-form': html_form}
            return JsonResponse({'success': False ,'html-form': htm, 'message': errors}, status=400)
        return super().form_invalid(form)



class AtletaDetailView(DetailView):
    model = Atleta
    template_name = 'atletas/detail.html'
    context_object_name = 'atleta_detail'

    def get_context_data(self, **kwargs):
        context = super(AtletaDetailView, self).get_context_data(**kwargs)
        encomendas = EncomendaItem.objects.all()
        context['encomendas'] = encomendas
        return context
    
    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['atletas/datail_partial.html']
        return ['atletas/detail.html']

   
    
    

    

class AtletaUpdateView(UpdateView):
    model = Atleta
    form_class = AtletaForm
    template_name = 'atletas/atleta_form.html'
    success_url = reverse_lazy('atletas:atletas_list')

    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['atletas/atleta_form_partial.html']
        return ['atletas/atleta_form.html']

    def get_context_data(self, **kwargs):
        context = super(AtletaUpdateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        self.object = form.save()
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': True ,'message': "Atleta editado com sucesso!"})
        return super().form_valid(form)
    
    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            html_form = render_to_string(self.template_name, {'form': form}, request=self.request)
            htm = {'html-form': html_form}
            return JsonResponse({'success': False ,'html-form': htm}, status=400)
        return super().form_invalid(form)
    
    




def atletas_delete(request, pk):
    try:
        atleta = get_object_or_404(Atleta, pk=pk)
        atleta.delete()
        return JsonResponse({'success': True,'message': f"Atleta {atleta.nome} eliminado com sucesso!"})
    except:
        return JsonResponse({'success': False,'message': "Erro ao eliminar atleta!"}, status=400)
    

def gerar_pdf_lista_atletas(request):
    escalao = request.GET.get('escalao')
    nome_escalao = Equipas.objects.get(id=escalao).nome
    response = HttpResponse(content_type= 'aplication/pdf')
    response['Content-Disposition'] = 'attachment; filename="relatorio.pdf"'
    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []

    titulo_style = ParagraphStyle(
        'titulo',
        fontName='Helvetica-Bold',
        fontSize=18,
        textColor=colors.HexColor("#183153"),
        spaceAfter=40,
        alignment=TA_CENTER

    )
    elements.append(Paragraph(f"Lista de Atletas - {str(nome_escalao).upper() if escalao != 'todos' else nome_escalao}", titulo_style))
    data = [["Nome", "Data de Nascimento", "Número Camisola"]]
    if escalao == 'todos':
        atletas = Atleta.objects.all().order_by('data_nascimento')
    else:
        atletas = Atleta.objects.filter(equipa__id=escalao).order_by('data_nascimento')
    for atleta in atletas:
        data.append([atleta.nome,atleta.data_nascimento, atleta.numero])
    table = Table(data)
    table.setStyle(TableStyle([('GRID', (0, 0), (-1, -1), 1, colors.black)]))
    elements.append(table)
    doc.build(elements)
    return response

def gerar_pdf_camisolas_atletas(request):
    escalao = request.GET.get('escalao')
    print(escalao)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="relatorio.pdf"'
    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []

    titulo_style = ParagraphStyle(
        'titulo',
        fontName='Helvetica-Bold',
        fontSize=18,
        textColor=colors.HexColor("#183153"),
        spaceAfter=40,
        alignment=TA_CENTER

    )
    elements.append(Paragraph("Relatório de Camisolas", titulo_style))
    data = [["Nome", "Número", 'Tipo', "Tamanho"]]
    if escalao == 'todos':
        atletas = Atleta.objects.all().order_by('data_nascimento')
    else:
        atletas = Atleta.objects.filter(equipa__id=escalao).order_by('data_nascimento')
    encomendas_equipamento_jogo = EncomendaItem.objects.filter(encomenda__atleta__in=atletas,equipamento__nome__in=["jogo principal", "guarda-redes azul"]).order_by('encomenda__atleta__data_nascimento')
    for equipamento in encomendas_equipamento_jogo:
        data.append([str(equipamento.encomenda.atleta.nome_camisola).title(), str(equipamento.encomenda.atleta.numero), str(equipamento.equipamento).capitalize(), str(equipamento.encomenda.tamanho)])

    table = Table(data)

    style = TableStyle([
    # Cabeçalho
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#4B7BEC")),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ('BOTTOMPADDING', (0, 0), (-1, 0), 12),

    # Bordas
    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CED4DA")),
    ])
    for i, row in enumerate(data[1:], start=1):
        bg_color = colors.HexColor("#F4F6F8") if i % 2 == 1 else colors.white
        style.add('BACKGROUND', (0, i), (-1, i), bg_color)

    table.setStyle(style)
    

    elements.append(table)
    doc.build(elements)
    return response



def atletas_escalao_json(request):
    escalao_filter = request.GET.get('escalao')
    print(escalao_filter)

    if escalao_filter == 'todos':
        print("todos")
        qs = Atleta.objects.all()

    else: 
        qs = Atleta.objects.filter(equipa__id=escalao_filter)
        print(qs)

    
    atletas_list = [
        {
            "id": atleta.id,
            "nome": atleta.nome,
            "numero": atleta.numero,
            "nome_camisola": atleta.nome_camisola,
            'data_nascimento': atleta.data_nascimento,
            "guarda_redes": atleta.guarda_redes,
            "equipa": atleta.equipa.nome if atleta.equipa else "",
        }
        for atleta in qs
    ]
    return JsonResponse({'resultados': atletas_list})

apps/atletas/templates/atletas/atleta_form.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

{% include 'atletas/atleta_form_partial.html' %}
{% endblock %}

apps/atletas/templates/atletas/atleta_form_partial.html
{% load static %}



<div class="container text-center" data-module="atletas">

  <div class="form-header">
    <div class="titulo">{% if object %}Editar Atleta{% else %}Novo Atleta{% endif %}</div>
  </div>


<form method="post" id="form-new-atleta" enctype="multipart/form-data" {% if object %} data-url="{% url 'atletas:update_atleta' object.pk %}" {% else %} data-url="{% url 'atletas:create_atleta' %}" {% endif %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >Gravar entrada</button>
</form>
</div>


<script>
  flatpickr(".datepicker", {
    dateFormat: "Y-m-d",
    altInput: true,
    altFormat: "d/m/Y",
    locale: "pt"
  });
</script>


<script>
  window.urlAtletasList = "{% url 'atletas:atletas_list' %}";
</script>

apps/atletas/templates/atletas/atletas_list.html
{% extends 'base.html' %}

{% block main %}
{% include 'atletas/atletas_list_partial.html' %}
{% endblock %}

apps/atletas/templates/atletas/atletas_list_partial.html
{% load static %}






<div class="container-atletas" data-module="atletas">


    <div class="header">
        <h1 class="titulo">Atletas AVS</h1>
        <select name="escalao" id="escalaoAtleta" onchange="filterAtletasEscala(this)">
            <option value="todosNA" disabled selected>Selecione um escalão</option>
            <option value="todos">Selecionar todos</option>
            {% for equipa in equipas %}
            <option value='{{equipa.id}}'>{{ equipa.nome }}</option>
            {% endfor %}
        </select>
        <a href="{% url 'atletas:create_atleta' %}" class="btn-add link-ajax">
            <span class="material-symbols-outlined">add</span>
            Novo Atleta
        </a>
    </div>
    
    <div class="table-responsive">
        <div class="table-container">
            <table class="table-atletas">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Data de Nascimento</th>
                        <th>Número</th>
                        <th>Nome Camisola</th>
                        <th>Guarda-redes</th>
                        <th>Equipa</th>
                        <th>Operações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for atleta in atletas %}
                    <tr>
                        <td><a href="{% url 'atletas:detail_atleta' atleta.id %}"
                                hx-get="{% url 'atletas:detail_atleta' atleta.id %}" hx-target="#conteudo-dinamico"
                                hx-targe="#conteudo-dinamico" hx-push-url="true" class="link-ajax">{{ atleta.nome }}</a></td>
                        <td>{{ atleta.data_nascimento|date:"d/m/Y" }}</td>
                        <td>{{ atleta.numero }}</td>
                        <td>{% if atleta.nome_camisola %}{{ atleta.nome_camisola }}{% else %}N/A{% endif %}</td>

                        <td><input type="checkbox" class="form-check-input" {% if atleta.guarda_redes %} checked {% endif %} disabled> </td>
                        <td>{% if atleta.equipa %}{{ atleta.equipa }}{% else %}N/A{% endif %}</td>
                        <td class="linha">
                            <a href="{% url 'atletas:update_atleta' atleta.id %}" class="link-ajax"><span
                                    class="material-symbols-outlined btn-operacoes"> edit</span></a>
                            <a href="#" class="link-ajax" onclick="deleteAtleta('{{ atleta.id }}', '{{ atleta.nome }}');"><span
                                    class="material-symbols-outlined btn-operacoes">
                                    delete
                                </span></a>
                            <a href="#"><span class="material-symbols-outlined btn-operacoes">shopping_cart_checkout</span></a>
                        </td>
                    </tr>
                    {% endfor %}


            </table>
        </div>



    </div>
    <div class="header">
        <div class="me-auto">
            <button type="button" class="btn-add" onclick="imprimirCamisolas(event)">
            <span class="material-symbols-outlined">print</span>
            Imprimir Nº Camisolas
            </button>
            <button type="button" class="btn-add" onclick="imprimirAtletas(event)">
                <span>Lista Atletas PDF</span>
            </button>
        </div>
    </div>

        
    
</div>

apps/atletas/templates/atletas/datail_partial.html
{% load static %}





<div class="container  text-center mt-5" data-module="atletas">
    <p class="fs-1 fw-bold">Detalhe {{atleta_detail.nome}}</p>

    <p><strong>Nome: </strong> {{atleta_detail.nome}}</p>
    <p><strong>Data Nascimento: </strong> {{atleta_detail.data_nascimento}}</p>
    <p><strong>Número: </strong> {{atleta_detail.numero}}</p>
    <p><strong>Encarregado: </strong> {{atleta_detail.encarregado}}</p>
    <p><strong>Telefone: </strong> {{atleta_detail.telefone}}</p>
    <p><strong>Email: </strong> {{atleta_detail.email}}</p>
    {% if  not atleta_detail.guarda_redes %}
    <p><strong>Guarda redes: </strong> Verdadeiro</p>
    {% endif %}
    <p><strong>Ficha: </strong> {{atleta_detail.ficha}}</p>


    <p class="fs-1 fw-bold">Encomendas</p>

    

</div>

apps/atletas/templates/atletas/detail.html
{% extends 'base.html' %}

{% block main %}

{% include 'atletas/datail_partial.html' %}
{% endblock %}