AFS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',  include('apps.core.urls'),name="home"),
    path('eumandoaqui/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jogos/', include('apps.jogos.urls')),
    path('equipamentos/', include('apps.equipamentos.urls',namespace='equipamentos')),
    path('core/', include('apps.core.urls')),
    path('atletas/', include('apps.atletas.urls',namespace='atletas')),
    path('api/', include('apps.api.urls',namespace='api'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/atletas/urls.py
from django.urls import path
from . import views
from apps.atletas.views import atletas_delete

app_name = 'atletas'

urlpatterns = [
    path('atletas_list/', views.AtletaListView.as_view(), name='atletas_list'),
    path('create_atleta/', views.AtletaCreateView.as_view(), name='create_atleta'),
    path('atleta_detail/<int:pk>/', views.AtletaDetailView.as_view(), name='detail_atleta'),
    path('update_atleta/<int:pk>/', views.AtletaUpdateView.as_view(), name='update_atleta'),
    path('delete_atleta/<int:pk>/', atletas_delete, name='delete_atleta'),
    path('pdf_camisolas_atletas/', views.gerar_pdf_camisolas_atletas, name='pdf_camisolas_atletas'),
    path('atletas_list_escalao/', views.atletas_escalao_json, name='atletals_list_escalao'),
    path('pdf_atletas_escalao_pdf/', views.gerar_pdf_lista_atletas, name='pdf_atletas_escalao'),
]

apps/equipamentos/urls.py
from django.urls import path
from . import views

app_name = 'equipamentos'
urlpatterns = [
    path('encomendas_equipamentos/<str:status>/', views.EncomendaEquipamentosListView.as_view(), name='encomendas_equipamentos_list'),
    path('create_encomenda_equipamentos/', views.EncomendaItemCreateView.as_view(), name='create_encomenda_equipamentos'),
    path('create_tamanho/', views.TamanhoCreateView.as_view(), name='create_tamanho'),
    path('update_tamanho/<int:pk>/', views.TamanhoUpdateView.as_view(), name='update_tamanho'),
    path('delete_tamanho/<int:pk>/', views.tamanho_delete, name='delete_tamanho'),
    path('create_equipamentos/', views.EquipamentosCreateView.as_view(), name='create_equipamentos'),
    path('update_equipamentos/<int:pk>/', views.EquipamentosUpdateView.as_view(), name='update_equipamentos'),
    path('delete_equipamentos/<int:pk>/', views.equipamentos_delete, name='delete_equipamentos'),
    path('encomenda_delete/<int:pk>/', views.encomenda_delete, name='encomenda_delete'),
    path('encomendas_por_atleta/<str:pk>/<str:status>/', views.encomendas_por_atleta, name='encomendas_por_atleta'),
    path('encomendas_uptade/<int:pk>/', views.EncomendaItemUpdateView.as_view(), name='encomendas_uptade'),
    path('alterar_estado_encomenda/<int:pk>/', views.alterar_estado_encomenda, name='alterar_estado_encomenda'),
    path('pdf_encomendas_atletas/', views.gerar_pdf_encomendas, name='pdf_encomendas_atletas'),
]

apps/jogos/urls.py
from django.urls import path
from apps.jogos import views

app_name = 'jogos'

urlpatterns = [
    path('jogos', views.JogosListView.as_view(), name='games_list'),
    path('novo_jogo', views.JogosCreateView.as_view(), name='new_game'),
    path('update_jogo/<int:pk>/', views.JogosUpdateView.as_view(), name='update_game'),
    path('delete_jogo/<int:pk>/', views.jogosDelete, name='delete_game'),
    path('nova_equipa', views.EquipaCreateView.as_view(), name='new_team'),
    path('update_equipa/<int:pk>/', views.EquipaUpdateView.as_view(), name='update_team'),
    path('delete_equipa/<int:pk>/', views.equipaDelete, name='delete_team'),
    path('estatistica_jogo/<int:pk>/', views.estatistica_jogo, name='estatistica_jogo'),
    path('iniciar_jogo/<int:id_jogo>', views.iniciar_jogo, name='iniciar_jogo'),
    path('substituicao_jogo/', views.substituicao_jogo, name='substituicao_jogo'),
    path('intervalo_jogo/<int:id_jogo>/', views.intervalo_jogo, name='intervalo_jogo'),
    path('finalizar_jogo/<int:id_jogo>/', views.finalizar_jogo, name='finalizar_jogo'),
    path('golo/<int:atleta_id>/<int:jogo_id>/', views.golo, name='golo'),
    path('golo_equipa/<int:id_jogo>/<int:id_equipa>/', views.golo_equipa, name='golo_equipa'),
    path('ajax/atletas-per-jogo/<int:equipa_id>/', views.atletas_por_equipa, name='atletas_por_equipa'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-pt">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'images\avs.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?v=2.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
    <script>
    const savedTheme = localStorage.getItem("theme");
    if(savedTheme === "dark" || (!savedTheme && window.matchMedia("(prefers-color-scheme: dark)").matches)) {
        document.documentElement.classList.add("dark-mode");
    }
    </script>
    <title>AFS sub-7</title>
</head>

<body>



    <div class="menu">
        <div></div>
        <div class="menu-links">
            <a href="{% url 'atletas:atletas_list' %}" class="btn-menu">Atletas</a>
            <a href="{% url 'equipamentos:encomendas_equipamentos_list' 'todos' %}" class="btn-menu">Encomendas</a>
            <a href="{% url 'jogos:games_list' %}" class="btn-menu">Jogos</a>
        </div>

        <button id="theme-toggle" class="btn btn-outline-secondary ">🌙 Escuro</button>
    </div>



    <div id="conteudo-dinamico" class="container-main mt-5">
        {% block main %}
        {% endblock %}
    </div>

{% csrf_token %}

</body>
<script>
    window.urlAtletasList = "{% url 'atletas:atletas_list' %}";
    window.urlEncomendasList = "{% url 'equipamentos:encomendas_equipamentos_list' 'todos' %}";
    window.urlJogosList = "{% url 'jogos:games_list' %}";
    window.urlSubstituicaoJogo = "{% url 'jogos:substituicao_jogo' %}";
    </script>



<script src="{% static 'js/geral.js'%}?v=2.0"></script>
<script src="{% static 'js/atletas.js' %}?v=2.0"></script>
<script src="{% static 'js/equipamentos.js' %}?v=2.0"></script>
<script src="{% static 'js/jogos.js'%}?v=2.0"></script>


</html>