AFS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',  include('apps.core.urls'),name="home"),
    path('eumandoaqui/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jogos/', include('apps.jogos.urls')),
    path('equipamentos/', include('apps.equipamentos.urls',namespace='equipamentos')),
    path('core/', include('apps.core.urls')),
    path('atletas/', include('apps.atletas.urls',namespace='atletas')),
    path('api/', include('apps.api.urls',namespace='api'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/jogos/urls.py
from django.urls import path
from apps.jogos import views

app_name = 'jogos'

urlpatterns = [
    path('jogos', views.JogosListView.as_view(), name='games_list'),
    path('novo_jogo', views.JogosCreateView.as_view(), name='new_game'),
    path('update_jogo/<int:pk>/', views.JogosUpdateView.as_view(), name='update_game'),
    path('delete_jogo/<int:pk>/', views.jogosDelete, name='delete_game'),
    path('nova_equipa', views.EquipaCreateView.as_view(), name='new_team'),
    path('update_equipa/<int:pk>/', views.EquipaUpdateView.as_view(), name='update_team'),
    path('delete_equipa/<int:pk>/', views.equipaDelete, name='delete_team'),
    path('estatistica_jogo/<int:pk>/', views.estatistica_jogo, name='estatistica_jogo'),
    path('iniciar_jogo/<int:id_jogo>', views.iniciar_jogo, name='iniciar_jogo'),
    path('substituicao_jogo/', views.substituicao_jogo, name='substituicao_jogo'),
    path('intervalo_jogo/<int:id_jogo>/', views.intervalo_jogo, name='intervalo_jogo'),
    path('finalizar_jogo/<int:id_jogo>/', views.finalizar_jogo, name='finalizar_jogo'),
    path('golo/<int:atleta_id>/<int:jogo_id>/', views.golo, name='golo'),
    path('golo_equipa/<int:id_jogo>/<int:id_equipa>/', views.golo_equipa, name='golo_equipa'),
    path('ajax/atletas-per-jogo/<int:equipa_id>/', views.atletas_por_equipa, name='atletas_por_equipa'),
    
]

apps/jogos/models.py
from datetime import timedelta
from django.db import models
from django.urls import reverse




class Equipas(models.Model):
    nome = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('jogos:games_list', )


class Jogos(models.Model):
    jornada = models.IntegerField()
    visitado = models.ForeignKey(Equipas, on_delete=models.CASCADE, related_name='visitado')
    visitante = models.ForeignKey(Equipas, on_delete=models.CASCADE, related_name='adversario')
    data = models.DateField(default=None)
    golos_visitado= models.IntegerField(default=0)
    golos_visitante = models.IntegerField(default=0)
    inicio_jogo = models.DateTimeField(default=None,null=True,blank=True)
    pausa = models.BooleanField(default=True, null=True, blank=True)
    fim_jogo = models.DateTimeField(default=None,null=True,blank=True)
    titulares = models.ManyToManyField('atletas.Atleta', related_name='titulares', blank=True)
    suplentes = models.ManyToManyField('atletas.Atleta', related_name='suplentes', blank=True)
    capitao = models.ForeignKey('atletas.Atleta', on_delete=models.CASCADE, related_name='capitao')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('jogos:games_list', )


    def __str__(self):
        return f"{self.jornada} - {self.visitado} vs {self.visitante}" 


class EstatisticaJogo(models.Model):
    jogo = models.ForeignKey(Jogos, on_delete=models.CASCADE)
    atleta = models.ForeignKey('atletas.Atleta', on_delete=models.CASCADE)
    golos = models.IntegerField(default=0)
    inicio = models.DateTimeField(default=None, null=True, blank=True)
    fim = models.DateTimeField(default=None, null=True, blank=True)
    total_minutos = models.FloatField(default=0)
    assistencias = models.IntegerField(default=0)
    em_campo = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('jogos:games_list', )

    @property
    def tempo_formatado_total_minutos(self):
        if not self.total_minutos:  # cobre None e 0
            return "00:00"

        delta = timedelta(minutes=self.total_minutos)
        total_segundos = int(delta.total_seconds())
       
        minutos, segundos = divmod(total_segundos, 60)
        if minutos < 10 and segundos < 10:
            return f"0{minutos}:0{segundos}"
        else:
            return f"{minutos:02d}:{segundos:02d}"

    def __str__(self):
        return f"{self.atleta} - {self.jogo}"

class HistoricoSubstituição(models.Model):
    jogo = models.ForeignKey(Jogos, on_delete=models.CASCADE)
    atleta = models.ForeignKey('atletas.Atleta', on_delete=models.CASCADE)
    entrou = models.DateTimeField(default=None,null=True,blank=True)
    saiu = models.DateTimeField(default=None,null=True,blank=True)
    total_minutos = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.atleta} - {self.jogo}"
    

apps/jogos/forms.py
from django import forms
from apps.atletas.models import Atleta
from apps.jogos.models import Jogos, EstatisticaJogo, Equipas


class JogosForm(forms.ModelForm):
    class Meta:
        model = Jogos
        fields = 'jornada', 'visitado', 'visitante', 'data', 'golos_visitado', 'golos_visitante', 'capitao','titulares', 'suplentes'
        widgets = {
            'jornada': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Jornada'}),
            'visitado': forms.Select(attrs={'class': 'form-control'}),
            'visitante': forms.Select(attrs={'class': 'form-control'}),
            'data': forms.DateInput(attrs={'class': 'form-control datepicker', 'placeholder': 'Data do jogo', 'type': 'date'}),
            'golos_visitado': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Golos visitado'}),
            'golos_visitante': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Golos visitante'}),
            'capitao': forms.Select(attrs={'class': 'form-control'}),
            'titulares': forms.SelectMultiple(attrs={'class': 'form-control','size': 10}),
            'suplentes': forms.SelectMultiple(attrs={'class': 'form-control','size': 10}),
        }


class EstatisticaJogoForm(forms.ModelForm):
    class Meta:
        model = EstatisticaJogo
        fields = '__all__'
        widgets = {
            'jogo': forms.Select(attrs={'class': 'form-control'}),
            'atleta': forms.Select(attrs={'class': 'form-control'}),
            'golos': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Golos'}),
            'assistencias': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Assistencias'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['atleta'].queryset = Atleta.objects.none()

class EquipasForm(forms.ModelForm):
    class Meta:
        model = Equipas
        fields = '__all__'
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/jogos/views.py
import json
from django.http import JsonResponse
from django.utils import timezone
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.template.loader import render_to_string
from apps.jogos.models import Jogos, Equipas, EstatisticaJogo, HistoricoSubstituição
from apps.jogos.forms import JogosForm, EquipasForm
from apps.atletas.models import Atleta


class JogosListView(ListView):
    model = Jogos
    template_name = 'jogos/jogos_list.html'
    context_object_name = 'jogos'

    def get_queryset(self):
        return super().get_queryset().order_by('data')

    def get_context_data(self, **kwargs):
        context = super(JogosListView, self).get_context_data(**kwargs)
        context['jogos'] = Jogos.objects.all()
        return context

    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['jogos/jogos_list_partial.html']
        return ['jogos/jogos_list.html']


class JogosCreateView(CreateView):
    model = Jogos
    template_name = 'jogos/jogos_form.html'
    form_class = JogosForm
    get_absolute_url = 'jogos_list'

    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['jogos/jogos_form_partial.html']
        return ['jogos/jogos_form.html']

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        self.object = form.save()
        visitado = self.object.visitado
        visitante = self.object.visitante
        jogo = self.object

        if visitado.nome.startswith('AVS'):
            for atleta in list(jogo.titulares.all()) + list(jogo.suplentes.all()):
                if not EstatisticaJogo.objects.filter(jogo=jogo, atleta=atleta).exists():
                    titular = True if atleta in list(jogo.titulares.all()) else False
                    EstatisticaJogo.objects.create(
                        jogo=jogo,
                        atleta=atleta,
                        golos=0,
                        assistencias=0,
                        total_minutos=0,
                        em_campo=titular
                    )
        elif visitante.nome.startswith('AVS'):
            for atleta in list(jogo.titulares.all()) + list(jogo.suplentes.all()):
                if not EstatisticaJogo.objects.filter(jogo=jogo, atleta=atleta).exists():
                    titular = True if atleta in list(jogo.titulares.all()) else False
                    EstatisticaJogo.objects.create(
                        jogo=jogo,
                        atleta=atleta,
                        golos=0,
                        assistencias=0,
                        total_minutos=0,
                        em_campo=titular
                    )
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': True, 'message': "Jogo criado com sucesso!"})
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            errors = form.errors.get_json_data()
            html_form = render_to_string('jogos/jogos_form_partial.html', {'form': form}, request=self.request)
            htm = {'html-form': html_form}
            return JsonResponse({'success': False, 'html-form': htm, 'message': errors}, status=400)
        return super().form_invalid(form)


class JogosUpdateView(UpdateView):
    model = Jogos
    template_name = 'jogos/jogos_form.html'
    form_class = JogosForm
    get_absolute_url = 'jogos_list'

    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['jogos/jogos_form_partial.html']
        return ['jogos/jogos_form.html']

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        self.object = form.save()
        visitado = self.object.visitado
        visitante = self.object.visitante
        jogo = self.object

        if visitado.nome.startswith('AVS'):
            titulares = jogo.titulares.all()
            for atleta in list(jogo.titulares.all()) + list(jogo.suplentes.all()):
                if not EstatisticaJogo.objects.filter(jogo=jogo, atleta=atleta).exists():
                    titular = True if atleta in list(jogo.titulares.all()) else False
                    EstatisticaJogo.objects.create(
                        jogo=jogo,
                        atleta=atleta,
                        golos=0,
                        assistencias=0,
                        total_minutos=0,
                        em_campo=titular,
                    )
        elif visitante.nome.startswith('AVS'):
            for atleta in list(jogo.titulares.all()) + list(jogo.suplentes.all()):
                if not EstatisticaJogo.objects.filter(jogo=jogo, atleta=atleta).exists():
                    titular = True if atleta in list(jogo.titulares.all()) else False
                    EstatisticaJogo.objects.create(
                        jogo=jogo,
                        atleta=atleta,
                        golos=0,
                        assistencias=0,
                        total_minutos=0,
                        em_campo=titular,
                    )

        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': True, 'message': "Jogo editado com sucesso!"})
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            html_form = render_to_string('jogos/jogos_form_partial.html', {'form': form}, request=self.request)
            htm = {'html-form': html_form}
            return JsonResponse({'success': False, 'html-form': htm}, status=400)
        return super().form_invalid(form)


def jogosDelete(request, pk):
    try:
        Jogos.objects.filter(pk=pk).delete()
        return JsonResponse({'success': True, 'message': "Jogo eliminado com sucesso!"})
    except:
        return JsonResponse({'success': False, 'message': "Erro ao eliminar jogo!"}, status=400)


class EquipaCreateView(CreateView):
    model = Equipas
    template_name = 'jogos/equipa_form.html'
    form_class = EquipasForm

    def form_valid(self, form):
        self.object = form.save()
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': True, 'message': "Equipa criada com sucesso!"})
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            errors = form.errors.get_json_data()
            html_form = render_to_string('jogos/equipa_form_partial.html', {'form': form}, request=self.request)
            htm = {'html-form': html_form}
            return JsonResponse({'success': False, 'html-form': htm, 'message': errors}, status=400)
        return super().form_invalid(form)

    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['jogos/equipa_form_partial.html']
        return ['jogos/equipa_form.html']


class EquipaUpdateView(UpdateView):
    model = Equipas
    template_name = 'jogos/equipa_form.html'
    form_class = EquipasForm

    def form_valid(self, form):
        self.object = form.save()
        if self.object.visitado.startwith('AVS'):
            for atleta in self.object.visitado.atletas.all():
                EstatisticaJogo.objects.create(
                    jogo=self.object,
                    atleta=atleta,
                    golos=0,
                    assistencias=0,
                    total_minutos=0
                )
        elif self.object.visitante.startwith('AVS'):
            for atleta in self.object.visitante.atletas.all():
                EstatisticaJogo.objects.create(
                    jogo=self.object,
                    atleta=atleta,
                    golos=0,
                    assistencias=0,
                    total_minutos=0
                )
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': True, 'message': "Equipa criada com sucesso!"})
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            errors = form.errors.get_json_data()
            html_form = render_to_string('jogos/equipa_form_partial.html', {'form': form}, request=self.request)
            htm = {'html-form': html_form}
            return JsonResponse({'success': False, 'html-form': htm, 'message': errors}, status=400)
        return super().form_invalid(form)

    def get_template_names(self):
        if self.request.headers.get('HX-Request') or self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return ['jogos/equipa_form_partial.html']
        return ['jogos/equipa_form.html']


def equipaDelete(request, pk):
    try:
        Equipas.objects.filter(pk=pk).delete()
        return JsonResponse({'success': True, 'message': "Equipa eliminada com sucesso!"})
    except:
        return JsonResponse({'success': False, 'message': "Erro ao eliminar equipa!"}, status=400)


def estatistica_jogo(request, pk):
    jogo = Jogos.objects.get(pk=pk)
    estatisticas = EstatisticaJogo.objects.filter(jogo=jogo).order_by('-em_campo')

    if jogo.visitado.nome.startswith("AVS"):
        equipa = jogo.visitado.nome
    elif jogo.visitante.nome.startswith("AVS"):

apps/jogos/templates/jogos/equipa_form.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
{% include 'jogos/jogos_form_partial.html' %}
{% endblock %}

apps/jogos/templates/jogos/equipa_form_partial.html
<div data-module="jogos" class="container">

    <div class="form-header text-center">
        <div class="titulo">{% if object %}Editar Equipa{% else %}Nova Equipa{% endif %}</div>
    </div>

    <div class="form-container">
        <form method="post" id="form-new-team" {% if object %}
         data-url="{% url 'jogos:update_team' object.pk %}" {% else %} data-url="{% url 'jogos:new_team' %}" {% endif %}>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary" >Criar Equipa</button>
        </form>
    </div>


</div>

apps/jogos/templates/jogos/estatisticas.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
{% include 'jogos/estatisticas_partial.html' %}
{% endblock %}

apps/jogos/templates/jogos/estatisticas_partial.html
<header class="p-4 d-flex flex-column align-items-center" data-module="jogos">
    <!-- Botões centralizados -->
    <div class="d-flex gap-2 mb-3 justify-content-center">
        {% if jogo.inicio %}
        <button type="button"
                id="btn-pause"
                class="btn btn-outline-secondary"
                data-action="intervalo-jogo"
                data-jogo="{{ jogo_id }}">
            <span class="material-symbols-outlined">pause_circle</span>
        </button>
        {% else %}

        <button type="button" id="btn-inicio" data-action="inicar-jogo" data-jogo="{{ jogo_id }}" class="btn
         btn-outline-secondary">
            <span class="material-symbols-outlined">play_circle</span>
        </button>
        {% endif %}



        
        
    </div>

   
    <div class="fs-2 fw-bold mb-2 text-center">Tempo</div>

    <div id="game-timer" data-inicio="{{ jogo.inicio }}"  class="display-1 fw-bold text-center">00:00</div>
</header>


<section class="p-4 d-flex flex-column align-items-center" data-module="jogos">
    <h2 class="font-bold"><span class="pointer"
    data-action="goloEquipa"
    data-jogo="{{jogo.id}}"
    data-equipaid="{{jogo.visitado.id}}">{{jogo.visitado}} ({{jogo.golos_visitado}}) - </span>
        <span class="pointer"
              data-action="goloEquipa"
              data-jogo="{{jogo.id}}"
              data-equipaid="{{jogo.visitante.id}}">{{jogo.visitante}} ({{jogo.golos_visitante}})</span></h2>
    <ul class="list-unstyled">
        {% for jogador in estatisticas %}
            <li class="d-flex align-items-center">
                <input type="checkbox" data-jogo="{{jogador.jogo.id}}" value="{{jogador.atleta.id}}" class="form-check-input atletasSelect"
                       data-action="alterarEmJogo"
                       data-jogo="{{jogador.jogo.id}}"
                       data-atleta="{{jogador.atleta.id}}"
                       name="jogadoresEmJogo"  {% if jogador.em_campo %} checked {% endif %}></input>
                <span class="ms-2 pointer"
                      data-action="golo"
                      data-jogo="{{jogo.id}}"
                      data-atleta="{{jogador.atleta.id}}"
                       >{% with nome_parts=jogador.atleta.nome.split %}
  {{ nome_parts.0 }} {{ nome_parts|last }}
{% endwith %}</span>
                <span class="ms-auto">{{jogador.golos}} golos</span>
                <span class="ms-2 tempo-decorrido-jogo" data-inicio="{{jogador.inicio|date:'c'}}"></span>
                <span class="ms-2">tempo: {{ jogador.tempo_formatado_total_minutos }}</span>
            </li>
        {% endfor %}
        
    </ul>
</section>  

apps/jogos/templates/jogos/jogos_form.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
{% include 'jogos/jogos_form_partial.html' %}
{% endblock %}

apps/jogos/templates/jogos/jogos_form_partial.html
<div class="container" data-module="jogos">



<div class="form-container">
    <div class="header d-flex justify-content-between">
    <a href="{% url 'jogos:games_list' %}" hx-get="{% url 'jogos:games_list' %}" hx-target="#conteudo-dinamico" hx-push-url="true" class="btn-add link-ajax">
        <span class="material-symbols-outlined">
                    undo
            </span>
        Voltar</a>
    <div class="titulo">{% if object %}Editar Jogo{% else %}Novo Jogo{% endif %}</div>

    <a href="{% url 'jogos:new_team' %}" hx-get="{% url 'jogos:new_team' %}" hx-target="#conteudo-dinamico"
       hx-push-url="true" class="btn-add link-ajax"><span class="material-symbols-outlined">add</span>
            Nova Equipa</a>

        </div>


    <form method="post" id="form-new-game" data-action="novo-jogo" {% if object %} data-url="{% url 'jogos:update_game' object.pk %}" {% else %} data-url="{% url 'jogos:new_game' %}" {% endif %}>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">{% if object %}Editar Jogo{% else %}Criar Jogo {% endif %}</button>
    </form>
</div>
</div>

apps/jogos/templates/jogos/jogos_list.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

{% include 'jogos/jogos_list_partial.html' %}
{% endblock %}

apps/jogos/templates/jogos/jogos_list_partial.html
{% load static%}



<div class="container" data-module="jogos">


    <div class="header">
        <h1 class="titulo">Lista de Jogos</h1>
        <a href="{% url 'jogos:new_game'  %}" hx-target="#conteudo-dinamico"
           hx-push-url="true" class="btn-add link-ajax" data-action="novo-jogo">
            <span class="material-symbols-outlined">add</span>
            Novo Jogo</a>


    </div>





    <div class="table-responsive">
        <table class="table-atletas">
            <thead>
                <tr>
                    <th scope="col">Visitado</th>
                    <th scope="col">Visitante</th>
                    <th>Resultado</th>
                    <th class="d-none d-md-table-cell" scope="col">Data</th>
                    <th>Operações</th>
                </tr>
            </thead>
            <tbody>
                {% for jogo in jogos %}
                <tr>
                    <td>{{ jogo.visitado }}</td>
                    <td>{{ jogo.visitante }}</td>
                    <td>{{ jogo.golos_visitado }} - {{ jogo.golos_visitante }}</td>
                    <td class="d-none d-md-table-cell">{{ jogo.data }}</td>
                    <td class="linha">
                        <a href="{% url 'jogos:update_game' jogo.pk %}" hx-get="{% url 'jogos:update_game' jogo.pk %}"
                            hx-target="#conteudo-dinamico" hx-push-url="true" class="link-ajax"><span
                                class="material-symbols-outlined btn-operacoes">
                                edit
                            </span></a>

                        <button type="button" class="btn-remove btn-operacoes"
                                data-action="resumoJogo"
                                data-jogoid="{{ jogo.pk }}"
                                ><span
                                class="material-symbols-outlined btn-operacoes">
                                timer_play
                            </span></button>
                        <button type="button" class="btn-remove btn-operacoes"><span class="material-symbols-outlined btn-operacoes">
                                sports_and_outdoors
                            </span></button>
                        <button type="button" class="btn-remove btn-operacoes"
                                data-action="eliminarJogo"
                                data-jogoid="{{ jogo.pk }}"
                                ><span class="material-symbols-outlined btn-operacoes">
                                delete
                            </span></button>

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
     </div>
</div>